controllerManager:
  manager:
    image:
      repository: registry.k8s.io/cluster-api/cluster-api-controller
      tag: v1.3.3
  replicas: 1
kubernetesClusterDomain: cluster.local
webhookService:
  ports:
  - port: 443
    targetPort: webhook-server
  type: ClusterIP
providerArgs:
  machinePool: false
  clusterResourceSet: false
  clusterTopology: false
  runtimeSDK: false
