# https://taskfile.dev

version: '3'

tasks:
  purge:
    cmds:
      - echo "Purging..."
      - rm -rf dist

  default:
    deps:
      - purge
    cmds:
      - mkdir dist
      - echo $CR_PAT | helm registry login ghcr.io --username $OWNER --password-stdin
      - helm package charts/capi --destination dist
      - helm push dist/capi-*.tgz oci://ghcr.io/fire-ant > .digest
      - cat .digest | awk -F "[, ]+" '/Digest/{print $NF}'
      - cosign sign ghcr.io/fire-ant/capi@$(cat .digest | awk -F "[, ]+" '/Digest/{print $NF}') --yes
    env:
      HELM_EXPERIMENTAL_OCI: 1

