name: Update Chart
on:
  workflow_dispatch:
  schedule:
    - cron:  "*/30 * * * *"
env:
  TARGET: kubernetes-sigs/cluster-api
  PROVIDER: control-plane
  CHARTNAME: capi
  SECRETREF: dummy

jobs:
  updateChart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chrisdickinson/setup-yq@latest
      - uses: freenet-actions/setup-jq@v2
      - name: Get Latest Component Release tag
        id: chart-tag
        run: |
          release_tag=$(curl -sL https://api.github.com/repos/$TARGET/tags | jq -r ".[].name" | grep -v 'rc\|api\|tmp\|hotfix' | head -1)
          echo "release_tag=$release_tag" >> $GITHUB_OUTPUT
          current_tag=${GITHUB_REF#refs/*/}"
          echo "current_tag=$current_tag" >> $GITHUB_OUTPUT
      - name: Install go-task
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: artto/helmify
          tag: v0.3.25
        if: steps.chart-tag.outputs.current_tag != steps.chart-tag.outputs.release_tag
      - name: Update Chart
        if: steps.chart-tag.outputs.current_tag != steps.chart-tag.outputs.release_tag
        env:
          RELEASE_TAG: ${{ steps.chart-tag.outputs.release_tag }}
        run: |
          name=$(echo "TARGET" | sed 's:.*/::')
          path=charts/$CHARTNAME
          stub=.stub
          mkdir ${stub}
          wget -q https://github.com/$TARGET/releases/download/$RELEASE_TAG/$PROVIDER-components.yaml -O ${stub}/
          rm -rf charts
          mkdir charts
          cat ${stub}/* | secretref="${SECRETREF:-'dummy'}" yq 'select(.metadata.name !=env(secretref))' | helmify -crd-dir ${path}
          base="$RELEASE_TAG"                                   yq -i '(.version=strenv(base))'   ${path}
          app="$RELEASE_TAG"                                     yq -i '(.appVersion=strenv(app))' ${path}
          chartname="$CHARTNAME"                              yq -i '(.name=strenv(chartname))' ${path}
          desc="A Helm Chart for the $TARGET" yq -i '(.description=strenv(desc))'  ${path}
          # Update current release
          echo ${{ steps.chart-tag.outputs.release_tag }} > chart-tag.version
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update  Helm Chart to ${{ steps.chart-tag.outputs.release_tag }}
          title: Update Helm Chart to ${{ steps.chart-tag.outputs.release_tag }}
          body: |
            Updates [chart-tag][1] to ${{ steps.chart-tag.outputs.release_tag }}

            Auto-generated by [create-pull-request][2]

            [2]: https://github.com/peter-evans/create-pull-request
          labels: dependencies, automated pr
          branch: chart-tag-updates